keys:
- &sydney_id 7bd239076aeddb164805f794a3e735d6c0921b17
- &global_dev age12yx655hzl0lv7afwm2f069umst8gd6d5hmly5r3q28nl3m8sxs2sfm7awf
- &system_t3mpt0n age1ydjdl44py0ghlldry7rwq4w599kmrdx9uzvy2g9aw5d94ulfg3vsk4m3tm
creation_rules:
- path_regex: ^sops/[^/]+\.(yaml|json|env|ini)$
  key_groups:
  - age:
    - *system_t3mpt0n
    - *global_dev
- path_regex: ^home/modules/crypt/sops/.*.yaml
  key_groups:
  - pgp:
    - *sydney_id
