# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."stick0".device = "/dev/disk/by-uuid/39af3d4f-05a1-467f-9a5f-326e78f8ad51";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@nixconfig" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4765ece6-5cda-4ef0-ba1f-0a83017a9c74";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
