# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2d1ff13c-1000-4b6e-93cd-a6973509dc2a";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."stick".device = "/dev/disk/by-uuid/10af15ba-8377-43d8-aaee-b40f4ca01983";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2d1ff13c-1000-4b6e-93cd-a6973509dc2a";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2d1ff13c-1000-4b6e-93cd-a6973509dc2a";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/2d1ff13c-1000-4b6e-93cd-a6973509dc2a";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/2d1ff13c-1000-4b6e-93cd-a6973509dc2a";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/2d1ff13c-1000-4b6e-93cd-a6973509dc2a";
      fsType = "btrfs";
      options = [ "subvol=@nixconfig" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/58DD-D244";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f3u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
