(progn
  (load "/etc/nixos/emacs/modules/elpaca/config.el")
  (load "/etc/nixos/emacs/modules/UI.el")
  (load "/etc/nixos/emacs/modules/org.el")
  (load "/etc/nixos/emacs/modules/startup.el")
  (load "/etc/nixos/emacs/modules/media.el")
  (load "/etc/nixos/emacs/modules/prgm.el")
  (load "/etc/nixos/emacs/modules/dired.el")
  (load "/etc/nixos/emacs/modules/other.el")
  (load "/etc/nixos/emacs/modules/email.el"))
