name: "EmulationStation Desktop-Edition"
on:
  pull_request:
    push:
      jobs:
        tests:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
              - uses: cachix/install-nix-action@v20
                with:
                  nix_path: nixpkgs=channel:nixos-unstable
                  - uses: cachix/cachix-action@v12
                    with:
                      name: emulationstation-desktop-edition
                      authToken: '${{ secrets.CACHIX_ESDE_AUTHTOKEN }}'
                      - run: nix-build -E 'let pkgs = import <nixpkgs> { }; in pkgs.callPackage ./packages/es-de/default.nix {}'
